//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRHReaderFrameWorkFarmTojasProcessor.TojasServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TojasServiceWCF.IRfidGatewayService")]
    public interface IRfidGatewayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRfidGatewayService/TermelesbeAd", ReplyAction="http://tempuri.org/IRfidGatewayService/TermelesbeAdResponse")]
        bool TermelesbeAd(string rfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRfidGatewayService/TermelesbeAd", ReplyAction="http://tempuri.org/IRfidGatewayService/TermelesbeAdResponse")]
        System.Threading.Tasks.Task<bool> TermelesbeAdAsync(string rfid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRfidGatewayServiceChannel : VRHReaderFrameWorkFarmTojasProcessor.TojasServiceWCF.IRfidGatewayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RfidGatewayServiceClient : System.ServiceModel.ClientBase<VRHReaderFrameWorkFarmTojasProcessor.TojasServiceWCF.IRfidGatewayService>, VRHReaderFrameWorkFarmTojasProcessor.TojasServiceWCF.IRfidGatewayService {
        
        public RfidGatewayServiceClient() {
        }
        
        public RfidGatewayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RfidGatewayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RfidGatewayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RfidGatewayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TermelesbeAd(string rfid) {
            return base.Channel.TermelesbeAd(rfid);
        }
        
        public System.Threading.Tasks.Task<bool> TermelesbeAdAsync(string rfid) {
            return base.Channel.TermelesbeAdAsync(rfid);
        }
    }
}
